# Default values for obzev0.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

daemon:
  image:
    repository: lumbrjx/obzev0-grpc-daemon
    tag: latest
    pullPolicy: IfNotPresent

controller:
  image:
    repository: lumbrjx/obzev0-k8s-controller
    tag: latest
    pullPolicy: IfNotPresent
  uiPort: 8090

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  grpcPort: 50051
  metricsPort: 2112
  uiPort: 8090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: obzev0.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  daemon:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
  controller:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
