// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: common/proto/packetManipulation/packetManipulation.proto

package packetManipulation

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PctmConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Server         string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Client         string                 `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	DurationConfig *DurationConfig        `protobuf:"bytes,3,opt,name=duration_config,json=durationConfig,proto3" json:"duration_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PctmConfig) Reset() {
	*x = PctmConfig{}
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PctmConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PctmConfig) ProtoMessage() {}

func (x *PctmConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PctmConfig.ProtoReflect.Descriptor instead.
func (*PctmConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP(), []int{0}
}

func (x *PctmConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *PctmConfig) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *PctmConfig) GetDurationConfig() *DurationConfig {
	if x != nil {
		return x.DurationConfig
	}
	return nil
}

type DurationConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds int32                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	DropRate        float32                `protobuf:"fixed32,2,opt,name=drop_rate,json=dropRate,proto3" json:"drop_rate,omitempty"`          // Added drop rate for packet dropping
	CorruptRate     float32                `protobuf:"fixed32,6,opt,name=corrupt_rate,json=corruptRate,proto3" json:"corrupt_rate,omitempty"` // Added rate for packet corruption
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DurationConfig) Reset() {
	*x = DurationConfig{}
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationConfig) ProtoMessage() {}

func (x *DurationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationConfig.ProtoReflect.Descriptor instead.
func (*DurationConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP(), []int{1}
}

func (x *DurationConfig) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *DurationConfig) GetDropRate() float32 {
	if x != nil {
		return x.DropRate
	}
	return 0
}

func (x *DurationConfig) GetCorruptRate() float32 {
	if x != nil {
		return x.CorruptRate
	}
	return 0
}

type RequestForManipulationProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *PctmConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestForManipulationProxy) Reset() {
	*x = RequestForManipulationProxy{}
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestForManipulationProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForManipulationProxy) ProtoMessage() {}

func (x *RequestForManipulationProxy) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForManipulationProxy.ProtoReflect.Descriptor instead.
func (*RequestForManipulationProxy) Descriptor() ([]byte, []int) {
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP(), []int{2}
}

func (x *RequestForManipulationProxy) GetConfig() *PctmConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ResponseFromManipulationProxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFromManipulationProxy) Reset() {
	*x = ResponseFromManipulationProxy{}
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFromManipulationProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFromManipulationProxy) ProtoMessage() {}

func (x *ResponseFromManipulationProxy) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFromManipulationProxy.ProtoReflect.Descriptor instead.
func (*ResponseFromManipulationProxy) Descriptor() ([]byte, []int) {
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseFromManipulationProxy) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_packetManipulation_packetManipulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_packetManipulation_packetManipulation_proto protoreflect.FileDescriptor

const file_common_proto_packetManipulation_packetManipulation_proto_rawDesc = "" +
	"\n" +
	"8common/proto/packetManipulation/packetManipulation.proto\x12\x16packetManipulationServ\x1a\x17validate/validate.proto\"\xa9\x01\n" +
	"\n" +
	"pctmConfig\x12\x1f\n" +
	"\x06server\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06server\x12\x1f\n" +
	"\x06client\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06client\x12Y\n" +
	"\x0fduration_config\x18\x03 \x01(\v2&.packetManipulationServ.DurationConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x0edurationConfig\"\xa6\x01\n" +
	"\x0eDurationConfig\x122\n" +
	"\x10duration_seconds\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x0fdurationSeconds\x12,\n" +
	"\tdrop_rate\x18\x02 \x01(\x02B\x0f\xfaB\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\bdropRate\x122\n" +
	"\fcorrupt_rate\x18\x06 \x01(\x02B\x0f\xfaB\f\n" +
	"\n" +
	"\x1d\x00\x00\x80?-\x00\x00\x00\x00R\vcorruptRate\"c\n" +
	"\x1bRequestForManipulationProxy\x12D\n" +
	"\x06config\x18\x01 \x01(\v2\".packetManipulationServ.pctmConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06config\"9\n" +
	"\x1dResponseFromManipulationProxy\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8a\x02\n" +
	"\x19PacketManipulationService\x12\x86\x01\n" +
	"\x16StartManipulationProxy\x123.packetManipulationServ.RequestForManipulationProxy\x1a5.packetManipulationServ.ResponseFromManipulationProxy\"\x00\x12d\n" +
	"\x15StopManipulationProxy\x12#.packetManipulationServ.StopRequest\x1a$.packetManipulationServ.StopResponse\"\x00B\x15Z\x13/packetManipulationb\x06proto3"

var (
	file_common_proto_packetManipulation_packetManipulation_proto_rawDescOnce sync.Once
	file_common_proto_packetManipulation_packetManipulation_proto_rawDescData []byte
)

func file_common_proto_packetManipulation_packetManipulation_proto_rawDescGZIP() []byte {
	file_common_proto_packetManipulation_packetManipulation_proto_rawDescOnce.Do(func() {
		file_common_proto_packetManipulation_packetManipulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_packetManipulation_packetManipulation_proto_rawDesc), len(file_common_proto_packetManipulation_packetManipulation_proto_rawDesc)))
	})
	return file_common_proto_packetManipulation_packetManipulation_proto_rawDescData
}

var file_common_proto_packetManipulation_packetManipulation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_packetManipulation_packetManipulation_proto_goTypes = []any{
	(*PctmConfig)(nil),                    // 0: packetManipulationServ.pctmConfig
	(*DurationConfig)(nil),                // 1: packetManipulationServ.DurationConfig
	(*RequestForManipulationProxy)(nil),   // 2: packetManipulationServ.RequestForManipulationProxy
	(*ResponseFromManipulationProxy)(nil), // 3: packetManipulationServ.ResponseFromManipulationProxy
	(*StopRequest)(nil),                   // 4: packetManipulationServ.StopRequest
	(*StopResponse)(nil),                  // 5: packetManipulationServ.StopResponse
}
var file_common_proto_packetManipulation_packetManipulation_proto_depIdxs = []int32{
	1, // 0: packetManipulationServ.pctmConfig.duration_config:type_name -> packetManipulationServ.DurationConfig
	0, // 1: packetManipulationServ.RequestForManipulationProxy.config:type_name -> packetManipulationServ.pctmConfig
	2, // 2: packetManipulationServ.PacketManipulationService.StartManipulationProxy:input_type -> packetManipulationServ.RequestForManipulationProxy
	4, // 3: packetManipulationServ.PacketManipulationService.StopManipulationProxy:input_type -> packetManipulationServ.StopRequest
	3, // 4: packetManipulationServ.PacketManipulationService.StartManipulationProxy:output_type -> packetManipulationServ.ResponseFromManipulationProxy
	5, // 5: packetManipulationServ.PacketManipulationService.StopManipulationProxy:output_type -> packetManipulationServ.StopResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_packetManipulation_packetManipulation_proto_init() }
func file_common_proto_packetManipulation_packetManipulation_proto_init() {
	if File_common_proto_packetManipulation_packetManipulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_packetManipulation_packetManipulation_proto_rawDesc), len(file_common_proto_packetManipulation_packetManipulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_packetManipulation_packetManipulation_proto_goTypes,
		DependencyIndexes: file_common_proto_packetManipulation_packetManipulation_proto_depIdxs,
		MessageInfos:      file_common_proto_packetManipulation_packetManipulation_proto_msgTypes,
	}.Build()
	File_common_proto_packetManipulation_packetManipulation_proto = out.File
	file_common_proto_packetManipulation_packetManipulation_proto_goTypes = nil
	file_common_proto_packetManipulation_packetManipulation_proto_depIdxs = nil
}
