apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-manager-rolebinding
  namespace: controller-system
subjects:
- kind: ServiceAccount
  name: controller-controller-manager
  namespace: controller-system
roleRef:
  kind: ClusterRole
  name: controller-manager-role
  apiGroup: rbac.authorization.k8s.io

