// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: networkChaos.proto

package networkChaos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkChaosService_StartBandwidthLimit_FullMethodName = "/networkChaos.NetworkChaosService/StartBandwidthLimit"
	NetworkChaosService_StopBandwidthLimit_FullMethodName  = "/networkChaos.NetworkChaosService/StopBandwidthLimit"
	NetworkChaosService_StartDNSChaos_FullMethodName       = "/networkChaos.NetworkChaosService/StartDNSChaos"
	NetworkChaosService_StopDNSChaos_FullMethodName        = "/networkChaos.NetworkChaosService/StopDNSChaos"
	NetworkChaosService_StartTCPReset_FullMethodName       = "/networkChaos.NetworkChaosService/StartTCPReset"
	NetworkChaosService_StopTCPReset_FullMethodName        = "/networkChaos.NetworkChaosService/StopTCPReset"
)

// NetworkChaosServiceClient is the client API for NetworkChaosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkChaosServiceClient interface {
	StartBandwidthLimit(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (*BandwidthResponse, error)
	StopBandwidthLimit(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	StartDNSChaos(ctx context.Context, in *DNSChaosRequest, opts ...grpc.CallOption) (*DNSChaosResponse, error)
	StopDNSChaos(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	StartTCPReset(ctx context.Context, in *TCPResetRequest, opts ...grpc.CallOption) (*TCPResetResponse, error)
	StopTCPReset(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type networkChaosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkChaosServiceClient(cc grpc.ClientConnInterface) NetworkChaosServiceClient {
	return &networkChaosServiceClient{cc}
}

func (c *networkChaosServiceClient) StartBandwidthLimit(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (*BandwidthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BandwidthResponse)
	err := c.cc.Invoke(ctx, NetworkChaosService_StartBandwidthLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkChaosServiceClient) StopBandwidthLimit(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, NetworkChaosService_StopBandwidthLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkChaosServiceClient) StartDNSChaos(ctx context.Context, in *DNSChaosRequest, opts ...grpc.CallOption) (*DNSChaosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSChaosResponse)
	err := c.cc.Invoke(ctx, NetworkChaosService_StartDNSChaos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkChaosServiceClient) StopDNSChaos(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, NetworkChaosService_StopDNSChaos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkChaosServiceClient) StartTCPReset(ctx context.Context, in *TCPResetRequest, opts ...grpc.CallOption) (*TCPResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TCPResetResponse)
	err := c.cc.Invoke(ctx, NetworkChaosService_StartTCPReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkChaosServiceClient) StopTCPReset(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, NetworkChaosService_StopTCPReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkChaosServiceServer is the server API for NetworkChaosService service.
// All implementations must embed UnimplementedNetworkChaosServiceServer
// for forward compatibility.
type NetworkChaosServiceServer interface {
	StartBandwidthLimit(context.Context, *BandwidthRequest) (*BandwidthResponse, error)
	StopBandwidthLimit(context.Context, *StopRequest) (*StopResponse, error)
	StartDNSChaos(context.Context, *DNSChaosRequest) (*DNSChaosResponse, error)
	StopDNSChaos(context.Context, *StopRequest) (*StopResponse, error)
	StartTCPReset(context.Context, *TCPResetRequest) (*TCPResetResponse, error)
	StopTCPReset(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedNetworkChaosServiceServer()
}

// UnimplementedNetworkChaosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkChaosServiceServer struct{}

func (UnimplementedNetworkChaosServiceServer) StartBandwidthLimit(context.Context, *BandwidthRequest) (*BandwidthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBandwidthLimit not implemented")
}
func (UnimplementedNetworkChaosServiceServer) StopBandwidthLimit(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopBandwidthLimit not implemented")
}
func (UnimplementedNetworkChaosServiceServer) StartDNSChaos(context.Context, *DNSChaosRequest) (*DNSChaosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDNSChaos not implemented")
}
func (UnimplementedNetworkChaosServiceServer) StopDNSChaos(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDNSChaos not implemented")
}
func (UnimplementedNetworkChaosServiceServer) StartTCPReset(context.Context, *TCPResetRequest) (*TCPResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTCPReset not implemented")
}
func (UnimplementedNetworkChaosServiceServer) StopTCPReset(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTCPReset not implemented")
}
func (UnimplementedNetworkChaosServiceServer) mustEmbedUnimplementedNetworkChaosServiceServer() {}
func (UnimplementedNetworkChaosServiceServer) testEmbeddedByValue()                             {}

// UnsafeNetworkChaosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkChaosServiceServer will
// result in compilation errors.
type UnsafeNetworkChaosServiceServer interface {
	mustEmbedUnimplementedNetworkChaosServiceServer()
}

func RegisterNetworkChaosServiceServer(s grpc.ServiceRegistrar, srv NetworkChaosServiceServer) {
	// If the following call pancis, it indicates UnimplementedNetworkChaosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkChaosService_ServiceDesc, srv)
}

func _NetworkChaosService_StartBandwidthLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BandwidthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkChaosServiceServer).StartBandwidthLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkChaosService_StartBandwidthLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkChaosServiceServer).StartBandwidthLimit(ctx, req.(*BandwidthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkChaosService_StopBandwidthLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkChaosServiceServer).StopBandwidthLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkChaosService_StopBandwidthLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkChaosServiceServer).StopBandwidthLimit(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkChaosService_StartDNSChaos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSChaosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkChaosServiceServer).StartDNSChaos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkChaosService_StartDNSChaos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkChaosServiceServer).StartDNSChaos(ctx, req.(*DNSChaosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkChaosService_StopDNSChaos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkChaosServiceServer).StopDNSChaos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkChaosService_StopDNSChaos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkChaosServiceServer).StopDNSChaos(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkChaosService_StartTCPReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TCPResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkChaosServiceServer).StartTCPReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkChaosService_StartTCPReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkChaosServiceServer).StartTCPReset(ctx, req.(*TCPResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkChaosService_StopTCPReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkChaosServiceServer).StopTCPReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkChaosService_StopTCPReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkChaosServiceServer).StopTCPReset(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkChaosService_ServiceDesc is the grpc.ServiceDesc for NetworkChaosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkChaosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "networkChaos.NetworkChaosService",
	HandlerType: (*NetworkChaosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBandwidthLimit",
			Handler:    _NetworkChaosService_StartBandwidthLimit_Handler,
		},
		{
			MethodName: "StopBandwidthLimit",
			Handler:    _NetworkChaosService_StopBandwidthLimit_Handler,
		},
		{
			MethodName: "StartDNSChaos",
			Handler:    _NetworkChaosService_StartDNSChaos_Handler,
		},
		{
			MethodName: "StopDNSChaos",
			Handler:    _NetworkChaosService_StopDNSChaos_Handler,
		},
		{
			MethodName: "StartTCPReset",
			Handler:    _NetworkChaosService_StartTCPReset_Handler,
		},
		{
			MethodName: "StopTCPReset",
			Handler:    _NetworkChaosService_StopTCPReset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networkChaos.proto",
}
