// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: networkChaos.proto

package networkChaos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BandwidthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	RateKbps      uint64                 `protobuf:"varint,2,opt,name=rate_kbps,json=rateKbps,proto3" json:"rate_kbps,omitempty"`
	BurstKb       uint32                 `protobuf:"varint,3,opt,name=burst_kb,json=burstKb,proto3" json:"burst_kb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthRequest) Reset() {
	*x = BandwidthRequest{}
	mi := &file_networkChaos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthRequest) ProtoMessage() {}

func (x *BandwidthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthRequest.ProtoReflect.Descriptor instead.
func (*BandwidthRequest) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{0}
}

func (x *BandwidthRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *BandwidthRequest) GetRateKbps() uint64 {
	if x != nil {
		return x.RateKbps
	}
	return 0
}

func (x *BandwidthRequest) GetBurstKb() uint32 {
	if x != nil {
		return x.BurstKb
	}
	return 0
}

type BandwidthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthResponse) Reset() {
	*x = BandwidthResponse{}
	mi := &file_networkChaos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthResponse) ProtoMessage() {}

func (x *BandwidthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthResponse.ProtoReflect.Descriptor instead.
func (*BandwidthResponse) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{1}
}

func (x *BandwidthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DNSChaosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	ListenAddr    string                 `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Upstream      string                 `protobuf:"bytes,4,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSChaosRequest) Reset() {
	*x = DNSChaosRequest{}
	mi := &file_networkChaos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSChaosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSChaosRequest) ProtoMessage() {}

func (x *DNSChaosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSChaosRequest.ProtoReflect.Descriptor instead.
func (*DNSChaosRequest) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{2}
}

func (x *DNSChaosRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DNSChaosRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *DNSChaosRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *DNSChaosRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

type DNSChaosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSChaosResponse) Reset() {
	*x = DNSChaosResponse{}
	mi := &file_networkChaos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSChaosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSChaosResponse) ProtoMessage() {}

func (x *DNSChaosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSChaosResponse.ProtoReflect.Descriptor instead.
func (*DNSChaosResponse) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{3}
}

func (x *DNSChaosResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TCPResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenAddr    string                 `protobuf:"bytes,1,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	ResetRate     float32                `protobuf:"fixed32,2,opt,name=reset_rate,json=resetRate,proto3" json:"reset_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPResetRequest) Reset() {
	*x = TCPResetRequest{}
	mi := &file_networkChaos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPResetRequest) ProtoMessage() {}

func (x *TCPResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPResetRequest.ProtoReflect.Descriptor instead.
func (*TCPResetRequest) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{4}
}

func (x *TCPResetRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *TCPResetRequest) GetResetRate() float32 {
	if x != nil {
		return x.ResetRate
	}
	return 0
}

type TCPResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPResetResponse) Reset() {
	*x = TCPResetResponse{}
	mi := &file_networkChaos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPResetResponse) ProtoMessage() {}

func (x *TCPResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPResetResponse.ProtoReflect.Descriptor instead.
func (*TCPResetResponse) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{5}
}

func (x *TCPResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_networkChaos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{6}
}

func (x *StopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_networkChaos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkChaos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_networkChaos_proto_rawDescGZIP(), []int{7}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_networkChaos_proto protoreflect.FileDescriptor

const file_networkChaos_proto_rawDesc = "" +
	"\n" +
	"\x12networkChaos.proto\x12\fnetworkChaos\"h\n" +
	"\x10BandwidthRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x1b\n" +
	"\trate_kbps\x18\x02 \x01(\x04R\brateKbps\x12\x19\n" +
	"\bburst_kb\x18\x03 \x01(\rR\aburstKb\"-\n" +
	"\x11BandwidthResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"}\n" +
	"\x0fDNSChaosRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\x12\x1f\n" +
	"\vlisten_addr\x18\x03 \x01(\tR\n" +
	"listenAddr\x12\x1a\n" +
	"\bupstream\x18\x04 \x01(\tR\bupstream\",\n" +
	"\x10DNSChaosResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Q\n" +
	"\x0fTCPResetRequest\x12\x1f\n" +
	"\vlisten_addr\x18\x01 \x01(\tR\n" +
	"listenAddr\x12\x1d\n" +
	"\n" +
	"reset_rate\x18\x02 \x01(\x02R\tresetRate\",\n" +
	"\x10TCPResetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf4\x03\n" +
	"\x13NetworkChaosService\x12X\n" +
	"\x13StartBandwidthLimit\x12\x1e.networkChaos.BandwidthRequest\x1a\x1f.networkChaos.BandwidthResponse\"\x00\x12M\n" +
	"\x12StopBandwidthLimit\x12\x19.networkChaos.StopRequest\x1a\x1a.networkChaos.StopResponse\"\x00\x12P\n" +
	"\rStartDNSChaos\x12\x1d.networkChaos.DNSChaosRequest\x1a\x1e.networkChaos.DNSChaosResponse\"\x00\x12G\n" +
	"\fStopDNSChaos\x12\x19.networkChaos.StopRequest\x1a\x1a.networkChaos.StopResponse\"\x00\x12P\n" +
	"\rStartTCPReset\x12\x1d.networkChaos.TCPResetRequest\x1a\x1e.networkChaos.TCPResetResponse\"\x00\x12G\n" +
	"\fStopTCPReset\x12\x19.networkChaos.StopRequest\x1a\x1a.networkChaos.StopResponse\"\x00B\x0fZ\r/networkChaosb\x06proto3"

var (
	file_networkChaos_proto_rawDescOnce sync.Once
	file_networkChaos_proto_rawDescData []byte
)

func file_networkChaos_proto_rawDescGZIP() []byte {
	file_networkChaos_proto_rawDescOnce.Do(func() {
		file_networkChaos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networkChaos_proto_rawDesc), len(file_networkChaos_proto_rawDesc)))
	})
	return file_networkChaos_proto_rawDescData
}

var file_networkChaos_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_networkChaos_proto_goTypes = []any{
	(*BandwidthRequest)(nil),  // 0: networkChaos.BandwidthRequest
	(*BandwidthResponse)(nil), // 1: networkChaos.BandwidthResponse
	(*DNSChaosRequest)(nil),   // 2: networkChaos.DNSChaosRequest
	(*DNSChaosResponse)(nil),  // 3: networkChaos.DNSChaosResponse
	(*TCPResetRequest)(nil),   // 4: networkChaos.TCPResetRequest
	(*TCPResetResponse)(nil),  // 5: networkChaos.TCPResetResponse
	(*StopRequest)(nil),       // 6: networkChaos.StopRequest
	(*StopResponse)(nil),      // 7: networkChaos.StopResponse
}
var file_networkChaos_proto_depIdxs = []int32{
	0, // 0: networkChaos.NetworkChaosService.StartBandwidthLimit:input_type -> networkChaos.BandwidthRequest
	6, // 1: networkChaos.NetworkChaosService.StopBandwidthLimit:input_type -> networkChaos.StopRequest
	2, // 2: networkChaos.NetworkChaosService.StartDNSChaos:input_type -> networkChaos.DNSChaosRequest
	6, // 3: networkChaos.NetworkChaosService.StopDNSChaos:input_type -> networkChaos.StopRequest
	4, // 4: networkChaos.NetworkChaosService.StartTCPReset:input_type -> networkChaos.TCPResetRequest
	6, // 5: networkChaos.NetworkChaosService.StopTCPReset:input_type -> networkChaos.StopRequest
	1, // 6: networkChaos.NetworkChaosService.StartBandwidthLimit:output_type -> networkChaos.BandwidthResponse
	7, // 7: networkChaos.NetworkChaosService.StopBandwidthLimit:output_type -> networkChaos.StopResponse
	3, // 8: networkChaos.NetworkChaosService.StartDNSChaos:output_type -> networkChaos.DNSChaosResponse
	7, // 9: networkChaos.NetworkChaosService.StopDNSChaos:output_type -> networkChaos.StopResponse
	5, // 10: networkChaos.NetworkChaosService.StartTCPReset:output_type -> networkChaos.TCPResetResponse
	7, // 11: networkChaos.NetworkChaosService.StopTCPReset:output_type -> networkChaos.StopResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_networkChaos_proto_init() }
func file_networkChaos_proto_init() {
	if File_networkChaos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networkChaos_proto_rawDesc), len(file_networkChaos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_networkChaos_proto_goTypes,
		DependencyIndexes: file_networkChaos_proto_depIdxs,
		MessageInfos:      file_networkChaos_proto_msgTypes,
	}.Build()
	File_networkChaos_proto = out.File
	file_networkChaos_proto_goTypes = nil
	file_networkChaos_proto_depIdxs = nil
}
