// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: common/proto/tcAnalyser/tcAnalyser.proto

package tcAnalyser

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TcConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcConfig) Reset() {
	*x = TcConfig{}
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcConfig) ProtoMessage() {}

func (x *TcConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcConfig.ProtoReflect.Descriptor instead.
func (*TcConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{0}
}

func (x *TcConfig) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type RequestForUserSpace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TcConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestForUserSpace) Reset() {
	*x = RequestForUserSpace{}
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestForUserSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForUserSpace) ProtoMessage() {}

func (x *RequestForUserSpace) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForUserSpace.ProtoReflect.Descriptor instead.
func (*RequestForUserSpace) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{1}
}

func (x *RequestForUserSpace) GetConfig() *TcConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ResponseFromUserSpace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFromUserSpace) Reset() {
	*x = ResponseFromUserSpace{}
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFromUserSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFromUserSpace) ProtoMessage() {}

func (x *ResponseFromUserSpace) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFromUserSpace.ProtoReflect.Descriptor instead.
func (*ResponseFromUserSpace) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseFromUserSpace) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{4}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_tcAnalyser_tcAnalyser_proto protoreflect.FileDescriptor

const file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc = "" +
	"\n" +
	"(common/proto/tcAnalyser/tcAnalyser.proto\x12\x0etcAnalyserServ\x1a\x17validate/validate.proto\"1\n" +
	"\bTcConfig\x12%\n" +
	"\tinterface\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tinterface\"G\n" +
	"\x13RequestForUserSpace\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.tcAnalyserServ.TcConfigR\x06config\"1\n" +
	"\x15ResponseFromUserSpace\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc1\x01\n" +
	"\x11TcAnalyserService\x12^\n" +
	"\x0eStartUserSpace\x12#.tcAnalyserServ.RequestForUserSpace\x1a%.tcAnalyserServ.ResponseFromUserSpace\"\x00\x12L\n" +
	"\rStopUserSpace\x12\x1b.tcAnalyserServ.StopRequest\x1a\x1c.tcAnalyserServ.StopResponse\"\x00B\rZ\v/tcAnalyserb\x06proto3"

var (
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescOnce sync.Once
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData []byte
)

func file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP() []byte {
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescOnce.Do(func() {
		file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc), len(file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc)))
	})
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData
}

var file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_tcAnalyser_tcAnalyser_proto_goTypes = []any{
	(*TcConfig)(nil),              // 0: tcAnalyserServ.TcConfig
	(*RequestForUserSpace)(nil),   // 1: tcAnalyserServ.RequestForUserSpace
	(*ResponseFromUserSpace)(nil), // 2: tcAnalyserServ.ResponseFromUserSpace
	(*StopRequest)(nil),           // 3: tcAnalyserServ.StopRequest
	(*StopResponse)(nil),          // 4: tcAnalyserServ.StopResponse
}
var file_common_proto_tcAnalyser_tcAnalyser_proto_depIdxs = []int32{
	0, // 0: tcAnalyserServ.RequestForUserSpace.config:type_name -> tcAnalyserServ.TcConfig
	1, // 1: tcAnalyserServ.TcAnalyserService.StartUserSpace:input_type -> tcAnalyserServ.RequestForUserSpace
	3, // 2: tcAnalyserServ.TcAnalyserService.StopUserSpace:input_type -> tcAnalyserServ.StopRequest
	2, // 3: tcAnalyserServ.TcAnalyserService.StartUserSpace:output_type -> tcAnalyserServ.ResponseFromUserSpace
	4, // 4: tcAnalyserServ.TcAnalyserService.StopUserSpace:output_type -> tcAnalyserServ.StopResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_tcAnalyser_tcAnalyser_proto_init() }
func file_common_proto_tcAnalyser_tcAnalyser_proto_init() {
	if File_common_proto_tcAnalyser_tcAnalyser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc), len(file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_tcAnalyser_tcAnalyser_proto_goTypes,
		DependencyIndexes: file_common_proto_tcAnalyser_tcAnalyser_proto_depIdxs,
		MessageInfos:      file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes,
	}.Build()
	File_common_proto_tcAnalyser_tcAnalyser_proto = out.File
	file_common_proto_tcAnalyser_tcAnalyser_proto_goTypes = nil
	file_common_proto_tcAnalyser_tcAnalyser_proto_depIdxs = nil
}
