// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: common/proto/tcAnalyser/tcAnalyser.proto

package tcAnalyser

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TcConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *TcConfig) Reset() {
	*x = TcConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcConfig) ProtoMessage() {}

func (x *TcConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcConfig.ProtoReflect.Descriptor instead.
func (*TcConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{0}
}

func (x *TcConfig) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type RequestForUserSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *TcConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *RequestForUserSpace) Reset() {
	*x = RequestForUserSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForUserSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForUserSpace) ProtoMessage() {}

func (x *RequestForUserSpace) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForUserSpace.ProtoReflect.Descriptor instead.
func (*RequestForUserSpace) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{1}
}

func (x *RequestForUserSpace) GetConfig() *TcConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ResponseFromUserSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseFromUserSpace) Reset() {
	*x = ResponseFromUserSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseFromUserSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFromUserSpace) ProtoMessage() {}

func (x *ResponseFromUserSpace) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFromUserSpace.ProtoReflect.Descriptor instead.
func (*ResponseFromUserSpace) Descriptor() ([]byte, []int) {
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseFromUserSpace) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_tcAnalyser_tcAnalyser_proto protoreflect.FileDescriptor

var file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x63, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x63, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x63, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x08, 0x54, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x25, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x09, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x30, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x74, 0x63, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x2e, 0x54,
	0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0x31, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x73, 0x0a, 0x11, 0x54, 0x63, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x23, 0x2e, 0x74, 0x63, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x25,
	0x2e, 0x74, 0x63, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x74, 0x63, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescOnce sync.Once
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData = file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc
)

func file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescGZIP() []byte {
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescOnce.Do(func() {
		file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData)
	})
	return file_common_proto_tcAnalyser_tcAnalyser_proto_rawDescData
}

var file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_tcAnalyser_tcAnalyser_proto_goTypes = []any{
	(*TcConfig)(nil),              // 0: tcAnalyserServ.TcConfig
	(*RequestForUserSpace)(nil),   // 1: tcAnalyserServ.RequestForUserSpace
	(*ResponseFromUserSpace)(nil), // 2: tcAnalyserServ.ResponseFromUserSpace
}
var file_common_proto_tcAnalyser_tcAnalyser_proto_depIdxs = []int32{
	0, // 0: tcAnalyserServ.RequestForUserSpace.config:type_name -> tcAnalyserServ.TcConfig
	1, // 1: tcAnalyserServ.TcAnalyserService.StartUserSpace:input_type -> tcAnalyserServ.RequestForUserSpace
	2, // 2: tcAnalyserServ.TcAnalyserService.StartUserSpace:output_type -> tcAnalyserServ.ResponseFromUserSpace
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_tcAnalyser_tcAnalyser_proto_init() }
func file_common_proto_tcAnalyser_tcAnalyser_proto_init() {
	if File_common_proto_tcAnalyser_tcAnalyser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TcConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RequestForUserSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseFromUserSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_tcAnalyser_tcAnalyser_proto_goTypes,
		DependencyIndexes: file_common_proto_tcAnalyser_tcAnalyser_proto_depIdxs,
		MessageInfos:      file_common_proto_tcAnalyser_tcAnalyser_proto_msgTypes,
	}.Build()
	File_common_proto_tcAnalyser_tcAnalyser_proto = out.File
	file_common_proto_tcAnalyser_tcAnalyser_proto_rawDesc = nil
	file_common_proto_tcAnalyser_tcAnalyser_proto_goTypes = nil
	file_common_proto_tcAnalyser_tcAnalyser_proto_depIdxs = nil
}
