// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/proto/tcAnalyser/tcAnalyser.proto

package tcAnalyser

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TcConfig with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TcConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TcConfig with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TcConfigMultiError, or nil
// if none found.
func (m *TcConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *TcConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetInterface()) < 1 {
		err := TcConfigValidationError{
			field:  "Interface",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TcConfigMultiError(errors)
	}

	return nil
}

// TcConfigMultiError is an error wrapping multiple validation errors returned
// by TcConfig.ValidateAll() if the designated constraints aren't met.
type TcConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TcConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TcConfigMultiError) AllErrors() []error { return m }

// TcConfigValidationError is the validation error returned by
// TcConfig.Validate if the designated constraints aren't met.
type TcConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TcConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TcConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TcConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TcConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TcConfigValidationError) ErrorName() string { return "TcConfigValidationError" }

// Error satisfies the builtin error interface
func (e TcConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTcConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TcConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TcConfigValidationError{}

// Validate checks the field values on RequestForUserSpace with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RequestForUserSpace) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestForUserSpace with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RequestForUserSpaceMultiError, or nil if none found.
func (m *RequestForUserSpace) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestForUserSpace) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConfig()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RequestForUserSpaceValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RequestForUserSpaceValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConfig()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RequestForUserSpaceValidationError{
				field:  "Config",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RequestForUserSpaceMultiError(errors)
	}

	return nil
}

// RequestForUserSpaceMultiError is an error wrapping multiple validation
// errors returned by RequestForUserSpace.ValidateAll() if the designated
// constraints aren't met.
type RequestForUserSpaceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestForUserSpaceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestForUserSpaceMultiError) AllErrors() []error { return m }

// RequestForUserSpaceValidationError is the validation error returned by
// RequestForUserSpace.Validate if the designated constraints aren't met.
type RequestForUserSpaceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestForUserSpaceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestForUserSpaceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestForUserSpaceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestForUserSpaceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestForUserSpaceValidationError) ErrorName() string {
	return "RequestForUserSpaceValidationError"
}

// Error satisfies the builtin error interface
func (e RequestForUserSpaceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestForUserSpace.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestForUserSpaceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestForUserSpaceValidationError{}

// Validate checks the field values on ResponseFromUserSpace with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResponseFromUserSpace) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResponseFromUserSpace with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResponseFromUserSpaceMultiError, or nil if none found.
func (m *ResponseFromUserSpace) ValidateAll() error {
	return m.validate(true)
}

func (m *ResponseFromUserSpace) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return ResponseFromUserSpaceMultiError(errors)
	}

	return nil
}

// ResponseFromUserSpaceMultiError is an error wrapping multiple validation
// errors returned by ResponseFromUserSpace.ValidateAll() if the designated
// constraints aren't met.
type ResponseFromUserSpaceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResponseFromUserSpaceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResponseFromUserSpaceMultiError) AllErrors() []error { return m }

// ResponseFromUserSpaceValidationError is the validation error returned by
// ResponseFromUserSpace.Validate if the designated constraints aren't met.
type ResponseFromUserSpaceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResponseFromUserSpaceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResponseFromUserSpaceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResponseFromUserSpaceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResponseFromUserSpaceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResponseFromUserSpaceValidationError) ErrorName() string {
	return "ResponseFromUserSpaceValidationError"
}

// Error satisfies the builtin error interface
func (e ResponseFromUserSpaceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResponseFromUserSpace.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResponseFromUserSpaceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResponseFromUserSpaceValidationError{}
