// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: common/proto/latency/latency.proto

package latency

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TcpConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqDelay      int32                  `protobuf:"varint,1,opt,name=reqDelay,proto3" json:"reqDelay,omitempty"`
	ResDelay      int32                  `protobuf:"varint,2,opt,name=resDelay,proto3" json:"resDelay,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Client        string                 `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpConfig) Reset() {
	*x = TcpConfig{}
	mi := &file_common_proto_latency_latency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpConfig) ProtoMessage() {}

func (x *TcpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_latency_latency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpConfig.ProtoReflect.Descriptor instead.
func (*TcpConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_latency_latency_proto_rawDescGZIP(), []int{0}
}

func (x *TcpConfig) GetReqDelay() int32 {
	if x != nil {
		return x.ReqDelay
	}
	return 0
}

func (x *TcpConfig) GetResDelay() int32 {
	if x != nil {
		return x.ResDelay
	}
	return 0
}

func (x *TcpConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *TcpConfig) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type RequestForTcp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TcpConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestForTcp) Reset() {
	*x = RequestForTcp{}
	mi := &file_common_proto_latency_latency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestForTcp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForTcp) ProtoMessage() {}

func (x *RequestForTcp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_latency_latency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForTcp.ProtoReflect.Descriptor instead.
func (*RequestForTcp) Descriptor() ([]byte, []int) {
	return file_common_proto_latency_latency_proto_rawDescGZIP(), []int{1}
}

func (x *RequestForTcp) GetConfig() *TcpConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ResponseFromTcp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFromTcp) Reset() {
	*x = ResponseFromTcp{}
	mi := &file_common_proto_latency_latency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFromTcp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFromTcp) ProtoMessage() {}

func (x *ResponseFromTcp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_latency_latency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFromTcp.ProtoReflect.Descriptor instead.
func (*ResponseFromTcp) Descriptor() ([]byte, []int) {
	return file_common_proto_latency_latency_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseFromTcp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_common_proto_latency_latency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_latency_latency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_latency_latency_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_common_proto_latency_latency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_latency_latency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_latency_latency_proto_rawDescGZIP(), []int{4}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_proto_latency_latency_proto protoreflect.FileDescriptor

const file_common_proto_latency_latency_proto_rawDesc = "" +
	"\n" +
	"\"common/proto/latency/latency.proto\x12\vlatencyServ\x1a\x17validate/validate.proto\"\x97\x01\n" +
	"\tTcpConfig\x12#\n" +
	"\breqDelay\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\breqDelay\x12#\n" +
	"\bresDelay\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\bresDelay\x12\x1f\n" +
	"\x06server\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06server\x12\x1f\n" +
	"\x06client\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06client\"I\n" +
	"\rRequestForTcp\x128\n" +
	"\x06config\x18\x01 \x01(\v2\x16.latencyServ.TcpConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06config\"+\n" +
	"\x0fResponseFromTcp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa6\x01\n" +
	"\x0eLatencyService\x12L\n" +
	"\x0eStartTcpServer\x12\x1a.latencyServ.RequestForTcp\x1a\x1c.latencyServ.ResponseFromTcp\"\x00\x12F\n" +
	"\rStopTcpServer\x12\x18.latencyServ.StopRequest\x1a\x19.latencyServ.StopResponse\"\x00B\n" +
	"Z\b/latencyb\x06proto3"

var (
	file_common_proto_latency_latency_proto_rawDescOnce sync.Once
	file_common_proto_latency_latency_proto_rawDescData []byte
)

func file_common_proto_latency_latency_proto_rawDescGZIP() []byte {
	file_common_proto_latency_latency_proto_rawDescOnce.Do(func() {
		file_common_proto_latency_latency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_latency_latency_proto_rawDesc), len(file_common_proto_latency_latency_proto_rawDesc)))
	})
	return file_common_proto_latency_latency_proto_rawDescData
}

var file_common_proto_latency_latency_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_latency_latency_proto_goTypes = []any{
	(*TcpConfig)(nil),       // 0: latencyServ.TcpConfig
	(*RequestForTcp)(nil),   // 1: latencyServ.RequestForTcp
	(*ResponseFromTcp)(nil), // 2: latencyServ.ResponseFromTcp
	(*StopRequest)(nil),     // 3: latencyServ.StopRequest
	(*StopResponse)(nil),    // 4: latencyServ.StopResponse
}
var file_common_proto_latency_latency_proto_depIdxs = []int32{
	0, // 0: latencyServ.RequestForTcp.config:type_name -> latencyServ.TcpConfig
	1, // 1: latencyServ.LatencyService.StartTcpServer:input_type -> latencyServ.RequestForTcp
	3, // 2: latencyServ.LatencyService.StopTcpServer:input_type -> latencyServ.StopRequest
	2, // 3: latencyServ.LatencyService.StartTcpServer:output_type -> latencyServ.ResponseFromTcp
	4, // 4: latencyServ.LatencyService.StopTcpServer:output_type -> latencyServ.StopResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_latency_latency_proto_init() }
func file_common_proto_latency_latency_proto_init() {
	if File_common_proto_latency_latency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_latency_latency_proto_rawDesc), len(file_common_proto_latency_latency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_latency_latency_proto_goTypes,
		DependencyIndexes: file_common_proto_latency_latency_proto_depIdxs,
		MessageInfos:      file_common_proto_latency_latency_proto_msgTypes,
	}.Build()
	File_common_proto_latency_latency_proto = out.File
	file_common_proto_latency_latency_proto_goTypes = nil
	file_common_proto_latency_latency_proto_depIdxs = nil
}
