// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: latency.proto

package latency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LatencyService_StartTcpServer_FullMethodName = "/latencyServ.LatencyService/StartTcpServer"
)

// LatencyServiceClient is the client API for LatencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LatencyServiceClient interface {
	StartTcpServer(ctx context.Context, in *RequestForTcp, opts ...grpc.CallOption) (*ResponseFromTcp, error)
}

type latencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLatencyServiceClient(cc grpc.ClientConnInterface) LatencyServiceClient {
	return &latencyServiceClient{cc}
}

func (c *latencyServiceClient) StartTcpServer(ctx context.Context, in *RequestForTcp, opts ...grpc.CallOption) (*ResponseFromTcp, error) {
	out := new(ResponseFromTcp)
	err := c.cc.Invoke(ctx, LatencyService_StartTcpServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LatencyServiceServer is the server API for LatencyService service.
// All implementations must embed UnimplementedLatencyServiceServer
// for forward compatibility
type LatencyServiceServer interface {
	StartTcpServer(context.Context, *RequestForTcp) (*ResponseFromTcp, error)
	mustEmbedUnimplementedLatencyServiceServer()
}

// UnimplementedLatencyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLatencyServiceServer struct {
}

func (UnimplementedLatencyServiceServer) StartTcpServer(context.Context, *RequestForTcp) (*ResponseFromTcp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTcpServer not implemented")
}
func (UnimplementedLatencyServiceServer) mustEmbedUnimplementedLatencyServiceServer() {}

// UnsafeLatencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LatencyServiceServer will
// result in compilation errors.
type UnsafeLatencyServiceServer interface {
	mustEmbedUnimplementedLatencyServiceServer()
}

func RegisterLatencyServiceServer(s grpc.ServiceRegistrar, srv LatencyServiceServer) {
	s.RegisterService(&LatencyService_ServiceDesc, srv)
}

func _LatencyService_StartTcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestForTcp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LatencyServiceServer).StartTcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LatencyService_StartTcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LatencyServiceServer).StartTcpServer(ctx, req.(*RequestForTcp))
	}
	return interceptor(ctx, in, info, handler)
}

// LatencyService_ServiceDesc is the grpc.ServiceDesc for LatencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LatencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "latencyServ.LatencyService",
	HandlerType: (*LatencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartTcpServer",
			Handler:    _LatencyService_StartTcpServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "latency.proto",
}
