//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlastRadius) DeepCopyInto(out *BlastRadius) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlastRadius.
func (in *BlastRadius) DeepCopy() *BlastRadius {
	if in == nil {
		return nil
	}
	out := new(BlastRadius)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackPolicy) DeepCopyInto(out *RollbackPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackPolicy.
func (in *RollbackPolicy) DeepCopy() *RollbackPolicy {
	if in == nil {
		return nil
	}
	out := new(RollbackPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkChaosConfig) DeepCopyInto(out *NetworkChaosConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkChaosConfig.
func (in *NetworkChaosConfig) DeepCopy() *NetworkChaosConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkChaosConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFaultConfig) DeepCopyInto(out *HTTPFaultConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFaultConfig.
func (in *HTTPFaultConfig) DeepCopy() *HTTPFaultConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPFaultConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExperimentStep) DeepCopyInto(out *ExperimentStep) {
	*out = *in
	out.LatencyServiceConfig = in.LatencyServiceConfig
	out.TcAnalyserServiceConfig = in.TcAnalyserServiceConfig
	out.PacketManipulationServiceConfig = in.PacketManipulationServiceConfig
	out.NetworkChaosConfig = in.NetworkChaosConfig
	out.HTTPFaultConfig = in.HTTPFaultConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExperimentStep.
func (in *ExperimentStep) DeepCopy() *ExperimentStep {
	if in == nil {
		return nil
	}
	out := new(ExperimentStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Obzev0Resource) DeepCopyInto(out *Obzev0Resource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Obzev0Resource.
func (in *Obzev0Resource) DeepCopy() *Obzev0Resource {
	if in == nil {
		return nil
	}
	out := new(Obzev0Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Obzev0Resource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Obzev0ResourceList) DeepCopyInto(out *Obzev0ResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Obzev0Resource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Obzev0ResourceList.
func (in *Obzev0ResourceList) DeepCopy() *Obzev0ResourceList {
	if in == nil {
		return nil
	}
	out := new(Obzev0ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Obzev0ResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Obzev0ResourceSpec) DeepCopyInto(out *Obzev0ResourceSpec) {
	*out = *in
	out.LatencyServiceConfig = in.LatencyServiceConfig
	out.TcAnalyserServiceConfig = in.TcAnalyserServiceConfig
	out.PacketManipulationServiceConfig = in.PacketManipulationServiceConfig
	out.NetworkChaosConfig = in.NetworkChaosConfig
	out.HTTPFaultConfig = in.HTTPFaultConfig
	in.BlastRadius.DeepCopyInto(&out.BlastRadius)
	out.RollbackPolicy = in.RollbackPolicy
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]ExperimentStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Obzev0ResourceSpec.
func (in *Obzev0ResourceSpec) DeepCopy() *Obzev0ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(Obzev0ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Obzev0ResourceStatus) DeepCopyInto(out *Obzev0ResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Obzev0ResourceStatus.
func (in *Obzev0ResourceStatus) DeepCopy() *Obzev0ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(Obzev0ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PacketManipulationConfig) DeepCopyInto(out *PacketManipulationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PacketManipulationConfig.
func (in *PacketManipulationConfig) DeepCopy() *PacketManipulationConfig {
	if in == nil {
		return nil
	}
	out := new(PacketManipulationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcAnalyserConfig) DeepCopyInto(out *TcAnalyserConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcAnalyserConfig.
func (in *TcAnalyserConfig) DeepCopy() *TcAnalyserConfig {
	if in == nil {
		return nil
	}
	out := new(TcAnalyserConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcpConfig) DeepCopyInto(out *TcpConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcpConfig.
func (in *TcpConfig) DeepCopy() *TcpConfig {
	if in == nil {
		return nil
	}
	out := new(TcpConfig)
	in.DeepCopyInto(out)
	return out
}
