// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: httpFault.proto

package httpFault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HTTPFaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenAddr    string                 `protobuf:"bytes,1,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	ErrorRate     float32                `protobuf:"fixed32,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	DelayMs       int32                  `protobuf:"varint,5,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	AbortRate     float32                `protobuf:"fixed32,6,opt,name=abort_rate,json=abortRate,proto3" json:"abort_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFaultRequest) Reset() {
	*x = HTTPFaultRequest{}
	mi := &file_httpFault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFaultRequest) ProtoMessage() {}

func (x *HTTPFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_httpFault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFaultRequest.ProtoReflect.Descriptor instead.
func (*HTTPFaultRequest) Descriptor() ([]byte, []int) {
	return file_httpFault_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPFaultRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *HTTPFaultRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *HTTPFaultRequest) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *HTTPFaultRequest) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *HTTPFaultRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *HTTPFaultRequest) GetAbortRate() float32 {
	if x != nil {
		return x.AbortRate
	}
	return 0
}

type HTTPFaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFaultResponse) Reset() {
	*x = HTTPFaultResponse{}
	mi := &file_httpFault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFaultResponse) ProtoMessage() {}

func (x *HTTPFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_httpFault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFaultResponse.ProtoReflect.Descriptor instead.
func (*HTTPFaultResponse) Descriptor() ([]byte, []int) {
	return file_httpFault_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPFaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_httpFault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_httpFault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_httpFault_proto_rawDescGZIP(), []int{2}
}

func (x *StopRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_httpFault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_httpFault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_httpFault_proto_rawDescGZIP(), []int{3}
}

func (x *StopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_httpFault_proto protoreflect.FileDescriptor

const file_httpFault_proto_rawDesc = "" +
	"\n" +
	"\x0fhttpFault.proto\x12\thttpFault\"\xca\x01\n" +
	"\x10HTTPFaultRequest\x12\x1f\n" +
	"\vlisten_addr\x18\x01 \x01(\tR\n" +
	"listenAddr\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x02R\terrorRate\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x05R\terrorCode\x12\x19\n" +
	"\bdelay_ms\x18\x05 \x01(\x05R\adelayMs\x12\x1d\n" +
	"\n" +
	"abort_rate\x18\x06 \x01(\x02R\tabortRate\"-\n" +
	"\x11HTTPFaultResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\vStopRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa5\x01\n" +
	"\x10HTTPFaultService\x12M\n" +
	"\x0eStartHTTPFault\x12\x1b.httpFault.HTTPFaultRequest\x1a\x1c.httpFault.HTTPFaultResponse\"\x00\x12B\n" +
	"\rStopHTTPFault\x12\x16.httpFault.StopRequest\x1a\x17.httpFault.StopResponse\"\x00B\fZ\n" +
	"/httpFaultb\x06proto3"

var (
	file_httpFault_proto_rawDescOnce sync.Once
	file_httpFault_proto_rawDescData []byte
)

func file_httpFault_proto_rawDescGZIP() []byte {
	file_httpFault_proto_rawDescOnce.Do(func() {
		file_httpFault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_httpFault_proto_rawDesc), len(file_httpFault_proto_rawDesc)))
	})
	return file_httpFault_proto_rawDescData
}

var file_httpFault_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_httpFault_proto_goTypes = []any{
	(*HTTPFaultRequest)(nil),  // 0: httpFault.HTTPFaultRequest
	(*HTTPFaultResponse)(nil), // 1: httpFault.HTTPFaultResponse
	(*StopRequest)(nil),       // 2: httpFault.StopRequest
	(*StopResponse)(nil),      // 3: httpFault.StopResponse
}
var file_httpFault_proto_depIdxs = []int32{
	0, // 0: httpFault.HTTPFaultService.StartHTTPFault:input_type -> httpFault.HTTPFaultRequest
	2, // 1: httpFault.HTTPFaultService.StopHTTPFault:input_type -> httpFault.StopRequest
	1, // 2: httpFault.HTTPFaultService.StartHTTPFault:output_type -> httpFault.HTTPFaultResponse
	3, // 3: httpFault.HTTPFaultService.StopHTTPFault:output_type -> httpFault.StopResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_httpFault_proto_init() }
func file_httpFault_proto_init() {
	if File_httpFault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_httpFault_proto_rawDesc), len(file_httpFault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_httpFault_proto_goTypes,
		DependencyIndexes: file_httpFault_proto_depIdxs,
		MessageInfos:      file_httpFault_proto_msgTypes,
	}.Build()
	File_httpFault_proto = out.File
	file_httpFault_proto_goTypes = nil
	file_httpFault_proto_depIdxs = nil
}
