// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: httpFault.proto

package httpFault

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HTTPFaultService_StartHTTPFault_FullMethodName = "/httpFault.HTTPFaultService/StartHTTPFault"
	HTTPFaultService_StopHTTPFault_FullMethodName  = "/httpFault.HTTPFaultService/StopHTTPFault"
)

// HTTPFaultServiceClient is the client API for HTTPFaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HTTPFaultServiceClient interface {
	StartHTTPFault(ctx context.Context, in *HTTPFaultRequest, opts ...grpc.CallOption) (*HTTPFaultResponse, error)
	StopHTTPFault(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type hTTPFaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHTTPFaultServiceClient(cc grpc.ClientConnInterface) HTTPFaultServiceClient {
	return &hTTPFaultServiceClient{cc}
}

func (c *hTTPFaultServiceClient) StartHTTPFault(ctx context.Context, in *HTTPFaultRequest, opts ...grpc.CallOption) (*HTTPFaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPFaultResponse)
	err := c.cc.Invoke(ctx, HTTPFaultService_StartHTTPFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hTTPFaultServiceClient) StopHTTPFault(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, HTTPFaultService_StopHTTPFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HTTPFaultServiceServer is the server API for HTTPFaultService service.
// All implementations must embed UnimplementedHTTPFaultServiceServer
// for forward compatibility.
type HTTPFaultServiceServer interface {
	StartHTTPFault(context.Context, *HTTPFaultRequest) (*HTTPFaultResponse, error)
	StopHTTPFault(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedHTTPFaultServiceServer()
}

// UnimplementedHTTPFaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHTTPFaultServiceServer struct{}

func (UnimplementedHTTPFaultServiceServer) StartHTTPFault(context.Context, *HTTPFaultRequest) (*HTTPFaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartHTTPFault not implemented")
}
func (UnimplementedHTTPFaultServiceServer) StopHTTPFault(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopHTTPFault not implemented")
}
func (UnimplementedHTTPFaultServiceServer) mustEmbedUnimplementedHTTPFaultServiceServer() {}
func (UnimplementedHTTPFaultServiceServer) testEmbeddedByValue()                          {}

// UnsafeHTTPFaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HTTPFaultServiceServer will
// result in compilation errors.
type UnsafeHTTPFaultServiceServer interface {
	mustEmbedUnimplementedHTTPFaultServiceServer()
}

func RegisterHTTPFaultServiceServer(s grpc.ServiceRegistrar, srv HTTPFaultServiceServer) {
	// If the following call pancis, it indicates UnimplementedHTTPFaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HTTPFaultService_ServiceDesc, srv)
}

func _HTTPFaultService_StartHTTPFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFaultServiceServer).StartHTTPFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFaultService_StartHTTPFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFaultServiceServer).StartHTTPFault(ctx, req.(*HTTPFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HTTPFaultService_StopHTTPFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPFaultServiceServer).StopHTTPFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HTTPFaultService_StopHTTPFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPFaultServiceServer).StopHTTPFault(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HTTPFaultService_ServiceDesc is the grpc.ServiceDesc for HTTPFaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HTTPFaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "httpFault.HTTPFaultService",
	HandlerType: (*HTTPFaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartHTTPFault",
			Handler:    _HTTPFaultService_StartHTTPFault_Handler,
		},
		{
			MethodName: "StopHTTPFault",
			Handler:    _HTTPFaultService_StopHTTPFault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "httpFault.proto",
}
